meta_product_name: "Got It!"
meta_title: "Got It! - Don't buy it, get it on Got It!"
meta_description: "Borrow things you need from your neighours for a fraction of the price of purchasing."
meta_image: "got-it-splash.jpg"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
